package red.eminence.commons.meta;

public enum Message
{
    SUCCESS,
    REQUEST_FAILED,
    ENTITY_NOT_FOUND,
    CORE_ENTITY_NOT_FOUND,
    CORE_ENTITY_CANNOT_MODIFY,
    SOMETHING_WENT_WRONG,
    VALIDATION_FAILED,
    REQUEST_PAYLOAD_VALIDATION_FAILED,
    METHOD_NOT_IMPLEMENTED,
    ACTION_COMPLETED_SUCCESSFULLY,
    DELETE_SUCCESSFUL,
    DEFAULT_VALUE_NOT_UPDATED,
    UNEXPECTED_EMPTY_BODY,
    MALFORMED_BODY_CONTENTS,
    PASSWORD_TOO_WEAK,
    INDETERMINABLE_ORIGIN,
    AUTHENTICATION_FAILED,
    TENANT_DISABLED,
    TENANT_NOT_FOUND,
    UNAUTHORIZED,
    PHONE_VERIFICATION_NEEDED,
    OTP_GENERATED,
    PERSISTENCE_FAILED,
    RESOURCE_EXISTS,
    ENTITY_VERSION_MISMATCH,
    UNSUPPORTED_OPERATION_EXCEPTION,
    TOKEN_REFRESHED
}